import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Utensils, Hammer, Mic, MessagesSquare, Settings, FlaskConical, Users } from "lucide-react";
import SiteNav from "@/components/site-nav";
import SiteFooter from "@/components/site-footer";
import FlowDemo from "@/components/flow-demo";
import "./light-home.css";

const services = [
 {name:"ServeFlow",title:"Reserveringen regelen",text:"Van online aanvraag tot bevestiging in één duidelijke flow. Minder handwerk rond je reserveringen.",href:"/serveflow",icon:Utensils,price:"€497",scope:"14 dagen · één locatie · één flow",note:"eenmalig"},
 {name:"TradeFlow",title:"Offerteaanvragen opvolgen",text:"Van aanvraag tot opvolging in één overzichtelijke flow. Je team houdt controle over de offerte.",href:"/tradeflow",icon:Hammer,price:"Op aanvraag",scope:"Implementatie na intake en scopeafspraak",note:""},
 {name:"Bonanza Voice",title:"Telefoontjes opvangen",text:"AI vangt oproepen op, beantwoordt basisvragen en noteert terugbelverzoeken. Ook buiten openingstijden in te richten.",href:"/bonanza-voice",icon:Mic,price:"Vanaf €1.495",scope:"Inrichting op basis van jouw gesprekstype",note:""},
];
export default function Home(){return <div className="light-site"><SiteNav light/><main id="main-content">
 <section className="bl-hero bl-container"><div className="bl-hero-copy"><p className="bl-eyebrow">Slimmere processen<br/>voor horeca, bouw en installatie</p><h1>Minder handwerk.<br/><span>Meer tijd voor<br className="bl-desktop-break"/> je klanten.</span></h1><p className="bl-lead">Wij richten reserveringen, offerteopvolging en telefonie slimmer in voor jouw bedrijf.</p><div className="bl-actions"><a className="bl-button" href="#demo">Bekijk de demo <ArrowRight size={18}/></a><Link className="bl-button bl-secondary" href="/contact">Plan kennismaking</Link></div><ul className="bl-assurances">{["Praktisch","Duidelijke werkwijze","Gewoon in begrijpelijke taal"].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></div><figure className="bl-hero-image"><Image src="/images/workday.webp" alt="Illustratie van een horecamedewerker en installateur met een tablet" fill priority sizes="(max-width:760px) 100vw, 55vw"/><figcaption>AI-gegenereerde sfeerbeelden · geen klantfoto’s</figcaption></figure></section>
 <section className="bl-section bl-container" id="oplossingen"><header className="bl-section-heading"><h2>Waar verliest jouw team tijd?</h2><p>Kies een proces. Wij helpen je het slimmer in te richten.</p></header><div className="bl-services">{services.map(s=><article key={s.name}><span className="bl-icon"><s.icon size={29}/></span><h3>{s.title}<span>{s.name}</span></h3><p>{s.text}</p><Link className="bl-link" href={s.href}>Meer over {s.name} <ArrowRight size={17}/></Link></article>)}</div></section>
 <section className="bl-section bl-mint" id="demo"><div className="bl-container"><header className="bl-section-heading"><h2>Zo kan jouw proces werken.</h2><p>Een eenvoudig voorbeeld, van aanvraag tot opvolging. Met fictieve gegevens.</p></header><FlowDemo/></div></section>
 <section className="bl-section bl-container bl-process" id="werkwijze"><header><h2>Van kennismaking<br/>naar werkende flow.</h2><p>In vier heldere stappen, samen met jouw team.</p></header><div className="bl-steps">{[{title:"Kennismaken",text:"We bespreken jouw situatie, uitdagingen en doelen.",icon:MessagesSquare},{title:"Inrichten",text:"We richten de gekozen flow in, samen met jouw team.",icon:Settings},{title:"Testen",text:"We testen de werking en finetunen waar nodig.",icon:FlaskConical},{title:"Evalueren",text:"We kijken wat goed werkt en wat een passende volgende stap is.",icon:Users}].map(s=><article key={s.title}><span className="bl-icon"><s.icon size={23}/></span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
 <section className="bl-section bl-mint" id="prijzen"><div className="bl-container"><header className="bl-price-heading"><h2>Begin met één proces.</h2><p>Kies wat past bij jouw situatie. We denken graag met je mee.</p></header><div className="bl-prices">{services.map(s=><article key={s.name}><div className="bl-price-title"><span className="bl-icon"><s.icon size={26}/></span><div><h3>{s.name}</h3><p>{s.title}</p></div></div><p className="bl-price">{s.price} <small>{s.note}</small></p><p>{s.scope}</p>{s.name==="ServeFlow"&&<p className="bl-small">Geen automatische verlenging.</p>}<Link className="bl-button" href="/contact">Bespreek je situatie <ArrowRight size={17}/></Link></article>)}</div><p className="bl-price-note">Alle prijzen excl. btw. Optioneel beheer en externe gebruikskosten apart. <Link href="/pricing">Bekijk scope en voorwaarden.</Link></p></div></section>
 </main><SiteFooter light/></div>;}
