"use client";
import { useRef, useState } from "react";
import { Utensils, Hammer, Mic, Mail, Check, Clock } from "lucide-react";
const examples=[
 {name:"ServeFlow",icon:Utensils,titles:["Aanvraag ontvangen","Bevestiging verstuurd","Herinnering gepland"],descriptions:["Een gast doet een reserveringsaanvraag via je website.","De gast ontvangt een bevestiging zodra de reservering is geaccepteerd.","Een herinnering helpt je gast de afspraak terug te vinden."],details:["Emma de Jong\n2 personen · diner\nVrijdag om 19:00\n\n‘Graag een tafel bij het raam.’","Hallo Emma,\n\nJe reservering voor 2 personen om 19:00 is bevestigd.\n\nTot dan!\nTeam Brasserie","Hallo Emma,\n\nMorgen zien we je graag voor je reservering om 19:00. Tot dan!\n\nTeam Brasserie"]},
 {name:"TradeFlow",icon:Hammer,titles:["Aanvraag ontvangen","Informatie compleet","Opvolging gepland"],descriptions:["Een klant vraagt een offerte aan.","Je team controleert de gegevens en stelt zelf de offerte vast.","Een opvolgtaak houdt de aanvraag in beeld."],details:["Sam Bakker\nAanvraag: vervanging cv-ketel\n\n‘Welke informatie hebben jullie nodig?’","Foto’s en situatie ontvangen.\n\nActie voor je team: beoordeel het werk en stel de offerte op.\n\nMenselijke controle blijft nodig.","Taak voor je team\n\nNeem contact op met Sam over de offerte en beantwoord eventuele vragen."]},
 {name:"Bonanza Voice",icon:Mic,titles:["Oproep opgevangen","Verzoek genoteerd","Terugbellen gepland"],descriptions:["De AI-assistent neemt een oproep aan.","De assistent vat de vraag samen voor je team.","Een medewerker neemt het persoonlijke vervolg over."],details:["Fictief gesprek\n\n‘Goedemiddag, ik wil een afspraak bespreken.’","Terugbelverzoek van Noor\n\nVraag: beschikbare momenten voor een intake.\n\nGeen afspraak zonder bevestiging.","Taak voor je team\n\nBel Noor terug om de beschikbaarheid te bespreken.\n\nEen medewerker bevestigt de afspraak."]}
];
export default function FlowDemo(){const [selected,setSelected]=useState(0);const [enabled,setEnabled]=useState(true);const tabs=useRef<(HTMLButtonElement|null)[]>([]);const demo=examples[selected];return <div className="bl-demo"><div className="bl-tabs" role="tablist" aria-label="Kies een voorbeeldproces">{examples.map((item,i)=><button key={item.name} ref={node=>{tabs.current[i]=node;}} id={`flow-tab-${i}`} role="tab" aria-selected={selected===i} aria-controls="flow-panel" tabIndex={selected===i?0:-1} onClick={()=>setSelected(i)} onKeyDown={e=>{let n=i;if(e.key==="ArrowRight")n=(i+1)%3;else if(e.key==="ArrowLeft")n=(i+2)%3;else if(e.key==="Home")n=0;else if(e.key==="End")n=2;else return;e.preventDefault();setSelected(n);tabs.current[n]?.focus();}}><item.icon size={20}/>{item.name}</button>)}</div><div className="bl-demo-panel" id="flow-panel" role="tabpanel" aria-labelledby={`flow-tab-${selected}`} tabIndex={0}>{demo.titles.map((title,i)=>{const Icon=[Mail,Check,Clock][i];return <article key={title}><div className="bl-step-number">Stap {i+1}</div><h3><Icon size={20}/>{title}</h3><p>{demo.descriptions[i]}</p>{i===2&&<label className="bl-toggle"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>{selected===0?"Herinnering 24 uur vooraf":"Opvolgtaak inschakelen"}</label>}<div className="bl-example">{i===2&&!enabled?"Uitgeschakeld in dit voorbeeld. Je team verzorgt zelf de opvolging.":demo.details[i]}</div></article>;})}</div><p className="bl-demo-note">Interactief voorbeeld — er worden geen berichten verstuurd of afspraken gemaakt.</p></div>;}
